### PR TITLE
Add a deprecation notice

### PR DESCRIPTION
**Pull request by jfmengels**
Add a deprecation notice to the Readme, so that people don't get their hopes up when they see this repo.

### CODE REVIEW

**Comment by kentcdodds** [comment]
Sorry for not adding this earlier. Thanks for adding it!

**Comment by jfmengels** [comment]
No worries ;)
I knew about it from before, and was hoping to tell @jdalton about it, because I feel like there is a lot of force pushes behind the scenes to keep the timeline clean.
Still sucks though...

**Comment by kentcdodds** [comment]
I may still work on it once I learn how to use serverless :-)

**Comment by jfmengels** [comment]
Please let me know then :D

**Comment by jfmengels** [comment]
PS: this is your first PR merge on this repo dealing with merge-less PRs ^^'

**Comment by jdalton** [comment]
rebase is my bff.

**Comment by kentcdodds** [comment]
I'll ping ya'll here if I get this working again.

**Pull request merged**
